#Test and publish
name: Publish
on:
  push:
    branches:
      - master
  pull_request:
      branches:
        - master
jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v4.1.1

        # Install .NET 8.0 SDK
      - name: Install .NET 8.0 SDK
        uses: actions/setup-dotnet@v4.0.0
        with: 
          dotnet-version: '8.0'

        # Cache NuGet packages to speed up subsequent builds
      - name: Cache NuGet packages
        uses: actions/cache@v4.0.0
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

          # Restore dependencies
      - name: Install dependencies
        run: dotnet restore
        # Build and test
  publish-project:
    runs-on: ubuntu-latest
    needs: test-project
    steps:
      - name: Check out Code
        uses: actions/checkout@v4.1.1

        # Install .NET 8.0 SDK
      - name: Install .NET 8.0 SDK
        uses: actions/setup-dotnet@v4.0.0
        with: 
          dotnet-version: '8.0'
        # Cache NuGet packages to speed up subsequent builds
      - name: Cache NuGet packages
        uses: actions/cache@v4.0.0
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          # Restore dependencies
      - name: Install dependencies
        run: dotnet restore

