#Test and publish
name: Publish
on:
  push:
    branches:
      - master
  pull_request:
      branches:
        - master
jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v4.1.1

        # Install .NET 8.0 SDK
      - name: Install .NET 8.0 SDK
        uses: actions/setup-dotnet@v4.0.0
        with: 
          dotnet-version: '8.0'

        # Cache NuGet packages to speed up subsequent builds
      - name: Cache NuGet packages
        uses: actions/cache@v4.0.0
        with:
          path: ~/.nuget
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

          # Restore dependencies
      - name: Install dependencies
        run: dotnet restore

        # Build and test
      - name: Build
        run: dotnet build --no-restore
      
        # Test
      - name: Test
        run: dotnet test --no-restore --verbosity normal
        
  publish-project:
    runs-on: ubuntu-latest
    needs: test-project
    steps:
      - name: Check out Code
        uses: actions/checkout@v4.1.1

        # Install .NET 8.0 SDK
      - name: Install .NET 8.0 SDK
        uses: actions/setup-dotnet@v4.0.0
        with: 
          dotnet-version: '8.0'
        # Cache NuGet packages to speed up subsequent builds
      - name: Cache NuGet packages
        uses: actions/cache@v4.0.0
        with:
          path: ~/.nuget
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          # Restore dependencies
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Create publish files
        run: dotnet publish --configuration Release --output ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3.0.0
        with:
          app-name: 'Webb-app-two'
          publish-profile: ${{ secrets.AZURE_WEB_APP_KEY }}
          package: './publish'

  create-issue:
    runs-on: ubuntu-latest
    needs: test-project
    steps:
      - name: Create Issue
        run: |
          echo "##[error]There is a problem with the code. Please check the build logs."
          echo "Tests Failed!"
